-- Bonesaw base install for `acore_characters`.
--
-- GENERATED by tools/db/build_base_snapshot.py -- do not hand-edit.
-- Applied by DBUpdater::Populate() only when the database is empty,
-- so this file is inert against an existing realm.

-- ---------------------------------------------------------------
-- 1. Structure: 63 tables that nothing else in the repo creates
-- ---------------------------------------------------------------

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ap_account_progress` (
  `account_id` int unsigned NOT NULL,
  `absorb_bonus` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ap_aether_sinks` (
  `account_id` int unsigned NOT NULL,
  `category` varchar(32) NOT NULL,
  `invested` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ap_item_attune` (
  `guid` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `progress` int unsigned NOT NULL DEFAULT '0',
  `attuned` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ap_item_snapshot` (
  `guid` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `quality` tinyint unsigned NOT NULL DEFAULT '1',
  `str` float NOT NULL DEFAULT '0',
  `agi` float NOT NULL DEFAULT '0',
  `sta` float NOT NULL DEFAULT '0',
  `int` float NOT NULL DEFAULT '0',
  `spi` float NOT NULL DEFAULT '0',
  `armor` float NOT NULL DEFAULT '0',
  `weapon_dps` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ap_reagent_archive` (
  `account_id` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `count` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ap_talents` (
  `guid` int unsigned NOT NULL,
  `stat_index` tinyint unsigned NOT NULL,
  `rank` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`stat_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_absorb` (
  `account_id` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `str` float NOT NULL DEFAULT '0',
  `agi` float NOT NULL DEFAULT '0',
  `sta` float NOT NULL DEFAULT '0',
  `intel` float NOT NULL DEFAULT '0',
  `spi` float NOT NULL DEFAULT '0',
  `armor` float NOT NULL DEFAULT '0',
  `sec_crit` float NOT NULL DEFAULT '0',
  `sec_hit` float NOT NULL DEFAULT '0',
  `sec_haste` float NOT NULL DEFAULT '0',
  `sec_expertise` float NOT NULL DEFAULT '0',
  `sec_armor_pen` float NOT NULL DEFAULT '0',
  `sec_resilience` float NOT NULL DEFAULT '0',
  `sec_attack_power` float NOT NULL DEFAULT '0',
  `sec_spell_power` float NOT NULL DEFAULT '0',
  `sec_defense` float NOT NULL DEFAULT '0',
  `sec_dodge` float NOT NULL DEFAULT '0',
  `sec_parry` float NOT NULL DEFAULT '0',
  `sec_block` float NOT NULL DEFAULT '0',
  `sec_mp5` float NOT NULL DEFAULT '0',
  `sec_health_regen` float NOT NULL DEFAULT '0',
  `sec_spell_pen` float NOT NULL DEFAULT '0',
  `sec_block_value` float NOT NULL DEFAULT '0',
  `item_level` smallint unsigned NOT NULL DEFAULT '1',
  `attune_pct` smallint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_currency` (
  `account_id` int unsigned NOT NULL,
  `item_id` int unsigned NOT NULL,
  `count` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_exalted_faction` (
  `account_id` int unsigned NOT NULL,
  `faction_id` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`faction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_key` (
  `account_id` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_meta` (
  `account_id` int unsigned NOT NULL,
  `corpses_looted` int unsigned NOT NULL DEFAULT '0',
  `fish_caught` int unsigned NOT NULL DEFAULT '0',
  `auto_attune_on` tinyint unsigned NOT NULL DEFAULT '0',
  `auto_attune_off` int unsigned NOT NULL DEFAULT '0',
  `auto_attune_ilvl` smallint unsigned NOT NULL DEFAULT '0',
  `attuned_de` tinyint unsigned NOT NULL DEFAULT '0',
  `hearth_uses` int unsigned NOT NULL DEFAULT '0',
  `jump_mode` tinyint unsigned NOT NULL DEFAULT '2',
  `ui_scale` tinyint unsigned NOT NULL DEFAULT '100',
  `shared_gold` int unsigned NOT NULL DEFAULT '0',
  `shared_honor` int unsigned NOT NULL DEFAULT '0',
  `shared_arena` int unsigned NOT NULL DEFAULT '0',
  `taxi_mask` varchar(255) NOT NULL DEFAULT '',
  `shared_inited` tinyint unsigned NOT NULL DEFAULT '0',
  `solo_queue` tinyint unsigned NOT NULL DEFAULT '0',
  `auto_mount` tinyint unsigned NOT NULL DEFAULT '0',
  `speed_cap` int unsigned NOT NULL DEFAULT '500',
  `riding_skill` int unsigned NOT NULL DEFAULT '0',
  `autoloot_on` tinyint unsigned NOT NULL DEFAULT '1',
  `autoloot_de` tinyint unsigned NOT NULL DEFAULT '0',
  `pull_radius` tinyint unsigned NOT NULL DEFAULT '0',
  `track_ore` tinyint unsigned NOT NULL DEFAULT '0',
  `track_herb` tinyint unsigned NOT NULL DEFAULT '0',
  `last_respec` int unsigned NOT NULL DEFAULT '0',
  `perk_epoch` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_mount` (
  `account_id` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_perk` (
  `account_id` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_perk_purchase` (
  `account_id` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  `paid` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_recipe` (
  `account_id` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_rep` (
  `account_id` int unsigned NOT NULL,
  `faction_id` smallint unsigned NOT NULL,
  `standing` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`faction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_reputation` (
  `account_id` int unsigned NOT NULL,
  `faction_id` int unsigned NOT NULL,
  `standing` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`faction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_skill` (
  `account_id` int unsigned NOT NULL,
  `skill_id` smallint unsigned NOT NULL,
  `skill_value` smallint unsigned NOT NULL DEFAULT '0',
  `skill_max` smallint unsigned NOT NULL DEFAULT '0',
  `skill_step` smallint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_account_taxi_maps` (
  `account_id` int unsigned NOT NULL,
  `map_id` smallint unsigned NOT NULL,
  `unlocked_at` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`map_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_achievement_value` (
  `achievement_id` int unsigned NOT NULL,
  `skill_points` int unsigned NOT NULL,
  PRIMARY KEY (`achievement_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_attune_milestone` (
  `account_id` int unsigned NOT NULL,
  `milestone` int unsigned NOT NULL,
  `earned_at` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`milestone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_autoloot_rule` (
  `account_id` int unsigned NOT NULL,
  `sort_idx` tinyint unsigned NOT NULL,
  `match_type` tinyint unsigned NOT NULL,
  `action` tinyint unsigned NOT NULL,
  `negate` tinyint unsigned NOT NULL DEFAULT '0',
  `quality` tinyint unsigned NOT NULL DEFAULT '0',
  `match_text` varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`account_id`,`sort_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_bug_report` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `report_type` varchar(16) NOT NULL DEFAULT 'bug',
  `is_critical` tinyint unsigned NOT NULL DEFAULT '0',
  `is_recurring` tinyint unsigned NOT NULL DEFAULT '0',
  `account_id` int unsigned NOT NULL,
  `character_guid` int unsigned NOT NULL,
  `character_name` varchar(24) NOT NULL DEFAULT '',
  `reported_at` int unsigned NOT NULL DEFAULT '0',
  `map_id` int unsigned NOT NULL DEFAULT '0',
  `zone_id` int unsigned NOT NULL DEFAULT '0',
  `zone_name` varchar(100) NOT NULL DEFAULT '',
  `pos_x` float NOT NULL DEFAULT '0',
  `pos_y` float NOT NULL DEFAULT '0',
  `pos_z` float NOT NULL DEFAULT '0',
  `player_level` tinyint unsigned NOT NULL DEFAULT '0',
  `target_entry` int unsigned NOT NULL DEFAULT '0',
  `target_name` varchar(100) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `posted` tinyint unsigned NOT NULL DEFAULT '0',
  `status` varchar(16) NOT NULL DEFAULT 'open',
  `resolution` text,
  `resolved_at` int unsigned NOT NULL DEFAULT '0',
  `discord_message_id` varchar(32) NOT NULL DEFAULT '',
  `github_issue_number` int unsigned DEFAULT NULL,
  `github_issue_url` varchar(255) NOT NULL DEFAULT '',
  `github_synced_at` int unsigned NOT NULL DEFAULT '0',
  `github_sync_attempts` smallint unsigned NOT NULL DEFAULT '0',
  `github_sync_error` varchar(500) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_github_issue_number` (`github_issue_number`),
  KEY `idx_posted` (`posted`,`id`),
  KEY `idx_account` (`account_id`),
  KEY `idx_status` (`status`,`id`),
  KEY `idx_github_sync` (`status`,`report_type`,`github_issue_number`,`id`),
  KEY `idx_priority` (`is_critical`,`posted`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=256 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_char_class_grant` (
  `guid` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  PRIMARY KEY (`guid`,`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_char_class_perk` (
  `guid` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_char_class_perk_spec` (
  `guid` int unsigned NOT NULL,
  `spec` tinyint unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  PRIMARY KEY (`guid`,`spec`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_char_rep_down` (
  `guid` int unsigned NOT NULL,
  `faction_id` smallint unsigned NOT NULL,
  PRIMARY KEY (`guid`,`faction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_char_spec` (
  `guid` int unsigned NOT NULL,
  `spec_spell` int unsigned NOT NULL,
  PRIMARY KEY (`guid`,`spec_spell`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_class_buff_unlock` (
  `account_id` int unsigned NOT NULL,
  `class` tinyint unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_combo` (
  `guid` int unsigned NOT NULL,
  `stacks` tinyint unsigned NOT NULL DEFAULT '0',
  `expires` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_item` (
  `item_guid` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `owner_guid` int unsigned NOT NULL,
  `xp` int unsigned NOT NULL DEFAULT '0',
  `level` smallint unsigned NOT NULL DEFAULT '1',
  `roll_str` int NOT NULL DEFAULT '0',
  `roll_agi` int NOT NULL DEFAULT '0',
  `roll_sta` int NOT NULL DEFAULT '0',
  `roll_int` int NOT NULL DEFAULT '0',
  `roll_spi` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_guid`),
  KEY `idx_lg_item_owner` (`owner_guid`),
  KEY `idx_lg_item_entry` (`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_perk_cost` (
  `spell_id` int unsigned NOT NULL,
  `cost` int unsigned NOT NULL,
  `requires_spell_id` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_quest_complete` (
  `account_id` int unsigned NOT NULL,
  `last_used` int unsigned NOT NULL DEFAULT '0',
  `bypass_count` int unsigned NOT NULL DEFAULT '0',
  `window_start` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_vault` (
  `account_id` int unsigned NOT NULL,
  `owner_guid` int unsigned NOT NULL,
  `kind` tinyint unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `item_count` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`owner_guid`,`kind`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_vault_reagent` (
  `item_entry` int unsigned NOT NULL,
  PRIMARY KEY (`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_wayfarer` (
  `guid` int unsigned NOT NULL,
  `account_id` int unsigned NOT NULL DEFAULT '0',
  `dmg_pct` tinyint unsigned NOT NULL DEFAULT '0',
  `changed_at` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`),
  KEY `idx_account` (`account_id`,`changed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_account_progress` (
  `account_id` int unsigned NOT NULL,
  `absorb_bonus` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_account_taxi` (
  `account_id` int unsigned NOT NULL,
  `node_id` smallint unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_aether_milestones` (
  `account_id` int unsigned NOT NULL,
  `milestone_type` varchar(32) NOT NULL,
  `milestone_id` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`milestone_type`,`milestone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_aether_sinks` (
  `account_id` int unsigned NOT NULL,
  `category` varchar(32) NOT NULL,
  `invested` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_attunements` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `preset` varchar(32) NOT NULL,
  `perKillBase` int NOT NULL,
  `bonusBoss` int NOT NULL,
  `capPerItem` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_preset` (`preset`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_aura_test_results` (
  `guid` int unsigned NOT NULL,
  `spell_id` int unsigned NOT NULL,
  `theme` varchar(16) NOT NULL DEFAULT '',
  `tier` tinyint NOT NULL DEFAULT '0',
  `result` varchar(16) NOT NULL DEFAULT 'UNTESTED',
  `notes` varchar(128) NOT NULL DEFAULT '',
  `tested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`guid`,`spell_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_bg_objectives` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `bg_type_id` tinyint unsigned NOT NULL,
  `objective_id` int unsigned NOT NULL,
  `essence_reward` int unsigned NOT NULL DEFAULT '25',
  `description` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bg_obj_unique` (`bg_type_id`,`objective_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_dissolved_items` (
  `account_id` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  PRIMARY KEY (`account_id`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_dungeon_leaderboard` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `map_id` int unsigned NOT NULL,
  `difficulty` tinyint unsigned NOT NULL DEFAULT '0',
  `account_id` int unsigned NOT NULL,
  `char_name` varchar(32) NOT NULL DEFAULT '',
  `clear_ms` int unsigned NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_map_time` (`map_id`,`difficulty`,`clear_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_dungeon_pb` (
  `account_id` int unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `difficulty` tinyint unsigned NOT NULL DEFAULT '0',
  `best_ms` int unsigned NOT NULL,
  `char_name` varchar(32) NOT NULL DEFAULT '',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`account_id`,`map_id`,`difficulty`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_item_attune` (
  `guid` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `progress` int unsigned NOT NULL DEFAULT '0',
  `attuned` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_item_snapshot` (
  `guid` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `quality` tinyint unsigned NOT NULL DEFAULT '1',
  `str` float NOT NULL DEFAULT '0',
  `agi` float NOT NULL DEFAULT '0',
  `sta` float NOT NULL DEFAULT '0',
  `int` float NOT NULL DEFAULT '0',
  `spi` float NOT NULL DEFAULT '0',
  `armor` float NOT NULL DEFAULT '0',
  `weapon_dps` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_mastery` (
  `guid` int unsigned NOT NULL,
  `aether` bigint unsigned NOT NULL DEFAULT '0',
  `mastery` int unsigned NOT NULL DEFAULT '0',
  `rate_xp` float NOT NULL DEFAULT '1',
  `rate_aether` float NOT NULL DEFAULT '1',
  `rate_boss` float NOT NULL DEFAULT '1',
  `rack_slots` tinyint NOT NULL DEFAULT '3',
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_mastery_spend` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `guid` int unsigned NOT NULL,
  `amount` int unsigned NOT NULL DEFAULT '0',
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_guid` (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_milestone_defs` (
  `id` int unsigned NOT NULL,
  `label` varchar(64) NOT NULL DEFAULT '',
  `aether_reward` int unsigned NOT NULL DEFAULT '50',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_milestones` (
  `guid` int unsigned NOT NULL,
  `milestone_id` int unsigned NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`guid`,`milestone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_quest_rewarded` (
  `guid` int unsigned NOT NULL,
  `quest_id` int unsigned NOT NULL,
  PRIMARY KEY (`guid`,`quest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_rack` (
  `guid` int unsigned NOT NULL,
  `slot_index` tinyint NOT NULL,
  `item_entry` int unsigned NOT NULL DEFAULT '0',
  `item_name` varchar(64) NOT NULL DEFAULT '',
  `item_quality` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`guid`,`slot_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_reagent_archive` (
  `account_id` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `count` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_residue` (
  `account_id` int unsigned NOT NULL,
  `amount` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_resonant_drops` (
  `account_id` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  `drop_count` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`,`item_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_session_state` (
  `guid` int unsigned NOT NULL,
  `clean_exit` tinyint(1) NOT NULL DEFAULT '0',
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `threat_level` tinyint unsigned NOT NULL DEFAULT '0',
  `threat_momentum` float NOT NULL DEFAULT '0',
  `threat_debt_kills` smallint unsigned NOT NULL DEFAULT '0',
  `threat_debt_mult` float NOT NULL DEFAULT '1',
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_sink_allocation` (
  `guid` int unsigned NOT NULL,
  `category` varchar(32) NOT NULL,
  `allocation` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_slot_mastery` (
  `guid` int unsigned NOT NULL,
  `slot` tinyint unsigned NOT NULL,
  `xp` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`slot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_talents` (
  `guid` int unsigned NOT NULL,
  `stat_index` tinyint unsigned NOT NULL,
  `rank` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`stat_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_telemetry` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `guid` int unsigned NOT NULL,
  `event` varchar(32) NOT NULL DEFAULT '',
  `value` float NOT NULL DEFAULT '0',
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_guid_event` (`guid`,`event`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `z_archive_ap_visage` (
  `guid` int unsigned NOT NULL,
  `primary_theme` varchar(32) NOT NULL DEFAULT 'worldsoul',
  `primary_enabled` tinyint NOT NULL DEFAULT '1',
  `secondary_theme` varchar(32) NOT NULL DEFAULT 'worldsoul',
  `secondary_enabled` tinyint NOT NULL DEFAULT '1',
  `flash_enabled` tinyint NOT NULL DEFAULT '1',
  `chat_flavor_enabled` tinyint NOT NULL DEFAULT '1',
  `primary_tier_selected` tinyint unsigned NOT NULL DEFAULT '0',
  `secondary_tier_selected` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;


-- ---------------------------------------------------------------
-- 2. Seed data for 6 config tables
--    (player-owned tables are intentionally left empty)
-- ---------------------------------------------------------------

INSERT INTO `lg_achievement_value` (`achievement_id`, `skill_points`) VALUES (456,10),(457,10),(458,10),(459,10),(460,10),(461,10),(462,10),(463,10),(464,10),(465,10),(466,10),(467,10),(1400,10),(1402,10),(1404,10),(1405,10),(1406,10),(1407,10),(1408,10),(1409,10),(1410,10),(1411,10),(1412,10),(1413,10),(1414,10),(1415,10),(1416,10),(1417,10),(1418,10),(1419,10),(1420,10),(1421,10),(1422,10),(1423,10),(1424,10),(1425,10),(1426,10),(1427,10),(1463,10),(3117,10),(3259,10),(4078,10),(4576,10);
INSERT INTO `lg_perk_cost` (`spell_id`, `cost`, `requires_spell_id`) VALUES (910002,1,0),(910003,1,0),(910004,1,0),(910005,1,0),(910006,1,0),(910007,1,0),(910008,12,0),(910009,1,0),(910038,2,0),(910039,26,910177),(910040,44,910039),(910043,2,0),(910044,8,910043),(910045,18,910044),(910046,6,0),(910047,6,0),(910048,6,0),(910063,1,0),(910064,3,910063),(910065,7,910064),(910066,13,910065),(910067,22,910066),(910068,34,910067),(910073,1,0),(910074,3,910073),(910075,7,910074),(910076,13,910075),(910077,22,910076),(910088,8,0),(910090,6,0),(910093,1,0),(910094,3,910093),(910095,7,910094),(910096,13,910095),(910097,22,910096),(910098,6,0),(910101,4,0),(910105,12,0),(910106,24,0),(910107,18,0),(910108,6,0),(910109,2,0),(910110,15,910109),(910111,55,910110),(910112,1,0),(910113,6,910112),(910114,16,910113),(910115,2,0),(910116,15,910115),(910117,55,910116),(910118,1,0),(910119,6,910118),(910120,16,910119),(910121,2,0),(910122,15,910121),(910123,55,910122),(910124,1,0),(910125,6,910124),(910126,16,910125),(910127,2,0),(910128,15,910127),(910129,55,910128),(910130,1,0),(910131,6,910130),(910132,16,910131),(910133,2,0),(910134,15,910133),(910135,55,910134),(910136,1,0),(910137,6,910136),(910138,16,910137),(910172,20,0),(910176,6,910038),(910177,14,910176),(910178,12,910101),(910179,26,910178),(910180,48,910179);
INSERT INTO `lg_vault_reagent` (`item_entry`) VALUES (1274),(12844),(18945),(19227),(19230),(19231),(19232),(19233),(19234),(19235),(19236),(19258),(19259),(19260),(19261),(19262),(19263),(19264),(19265),(19268),(19269),(19270),(19271),(19272),(19273),(19274),(19275),(19276),(19278),(19279),(19280),(19281),(19282),(19283),(19284),(19698),(19699),(19700),(19701),(19702),(19703),(19704),(19705),(19706),(19707),(19708),(19709),(19710),(19711),(19712),(19713),(19714),(19715),(21100),(22527),(22528),(22529),(25996),(42780);


-- ---------------------------------------------------------------
-- 3. Mark 39 pending revisions as applied
--    Their structure is in section 1 and their data in section 2.
--    They cannot be replayed: the updater runs files alphabetically
--    but these were written chronologically, and the orders differ.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `updates` (
  `name` varchar(200) NOT NULL,
  `hash` char(40) DEFAULT '',
  `state` enum('RELEASED','CUSTOM','MODULE','ARCHIVED','PENDING') NOT NULL DEFAULT 'RELEASED',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `speed` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_auto_attune_min_ilvl.sql', '9A7E4D25C470415D244672798049F8A0E9CF102F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_bomb_rank3_specmask.sql', 'A47F821E43475E121777A5AED15C1FBE35EA3D81', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear.sql', '8940F5E427E4A7145ED0799FE2579E9B8498850F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_account_currency.sql', '0A07110438734AFF1199D514C90B1330FCE15B1C', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_account_keys.sql', 'BA6D5CE3F677C05E6F312EA6F3053D95CA915C57', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_account_mounts.sql', '25ED73CFF56593363B4B4B77CA4CF93288A709CE', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_account_reputation.sql', 'AA6C525DC451511498D7656338DF014452DEC83B', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_account_taxi_maps.sql', 'C198EF3657C4D60936447B084930EA3ADBC57E70', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_attune_rescale.sql', 'AD78E52911467A7486424B35A950C69DCA21D2D3', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_attune_secondaries.sql', '1B3C5514EEC08E2A93F13B2E0140486A88B8C9DF', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_attunement_v2.sql', '2B61870B22CDFC185C14B80C10C4474DF6807F9C', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_auto_mount.sql', '067CC5048993A3721E85A2D3DCD3AF54EE3C4BCA', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_autoloot_toggle.sql', '3169804A0812DC4BCDB21A091C939E4387F8CEA6', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_bug_status.sql', '4714AE6DB11F516F8C436D1B305DF3BB76B7D621', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_class_perk_grants.sql', '55F3F26CCA5F93DC29E8EA79075F2E2DE50A7CB7', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_class_perks.sql', '17BA1626FDC03A8DD2F7B23622BBD7E16A86A0FE', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_emblems_accountwide.sql', 'F9716C76A377B29EC30078EF6FEC15F38A8E276C', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_emblems_leave_vault.sql', '425412346BB48E60858D10C4C5E7C60277F48FD8', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_gather_021.sql', '1EF2856B49FCD5824D1155FAC32A3A9545F72FEB', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_next_021.sql', 'A8833C55A3009CE9B8F5122F38795FC90D251EEC', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_perk_points.sql', 'DD6774ADCD891B8276CB55C9B04773A178722F0E', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_phantom_cooldowns.sql', '472B48FA703459D539D5466D1132C9DC3DEDEACE', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_progression.sql', '7CAF5E4B9D2FA3BAEB78D72284D7221A2626BE30', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_pull_radius.sql', '417F57E930CE2ADADBEE2F8A1BA9AF6DC8731BAF', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_quest_bypass.sql', '5D2A0F6E6A987496ADA8CC1BDAD3CC84EA995EAF', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_report_flags.sql', 'AE8416D2B4A09F547A2F0EB54AE2C063EEA983B0', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_shared_reseed.sql', '01EE7374E77607843C91817E2B808DF810EF1268', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_solo_queue.sql', '42E218E63FC4429227AD28EC1F54FFF4900771B2', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_support.sql', 'B40F357E7879595B118A1B1F93D501BE91344A3D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_support_github_sync.sql', '66AD8C80555EDC5D3B716FD8621A20132944D50D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_track_gather.sql', 'EED3E11FD051770253959B17C1D0B2BEAD8AC286', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_track_only.sql', 'C40EFDF5A1F681BC2044AB6C143915389971DECF', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_track_only_gather_021.sql', '1FC7C92F87411CAACBEFC905B5811C3BA81C8983', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_ui_scale.sql', 'C1DC028762F623A36FAF7A43A04EABC58CA87BF7', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_unbind_existing.sql', 'D5DA6E63279B0FFAEEF319FCD2F0024D9CBBC70B', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_vault_reagents.sql', 'CCA9B951F6E13452C22B92AC253CC86FFA56D8BA', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_wayfarer.sql', 'E5A869B261AB1F387118D509800A1E9742FD23D0', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_wayfarer_id_reuse.sql', '763C0E8AA95AAC1F4E07F7C5AB2562AD3BC8A9DD', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_reputation_team_scope.sql', 'BE904157E8F9286575DDA1E1F67C225E64E6E3F3', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
