[package]
name = "bonesaw-launcher"
version = "2.0.0"
edition = "2021"
build = "build.rs"
publish = false

[[bin]]
name = "Bonesaw"
path = "src/main.rs"

[dependencies]
sha2 = "0.10"
ureq = "2.12"

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security_Cryptography",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
