-- Bonesaw base install for `acore_world`.
--
-- GENERATED by tools/db/build_base_snapshot.py -- do not hand-edit.
-- Applied by DBUpdater::Populate() only when the database is empty,
-- so this file is inert against an existing realm.

-- ---------------------------------------------------------------
-- 1. Structure: 2 tables that nothing else in the repo creates
-- ---------------------------------------------------------------

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_dungeon_par` (
  `map_id` int unsigned NOT NULL COMMENT 'Map.dbc id',
  `difficulty` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '0=normal, 1=heroic (instance difficulty)',
  `par_sec` int unsigned NOT NULL COMMENT 'Par clear time in seconds',
  PRIMARY KEY (`map_id`,`difficulty`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Living Gear dungeon par times';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lg_zone_scale` (
  `zone_id` int unsigned NOT NULL COMMENT 'AreaTable zone id (parent zone, not sub-area)',
  `max_level` tinyint unsigned NOT NULL COMMENT 'Recommended max level for this zone',
  PRIMARY KEY (`zone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Living Gear zone scale overrides';
/*!40101 SET character_set_client = @saved_cs_client */;


-- ---------------------------------------------------------------
-- 2. Seed data for 2 config tables
--    (player-owned tables are intentionally left empty)
-- ---------------------------------------------------------------

INSERT INTO `lg_dungeon_par` (`map_id`, `difficulty`, `par_sec`) VALUES (33,0,1800),(36,0,1800),(43,0,1200),(48,0,1800),(189,0,3600),(289,0,3600),(389,0,600),(409,0,3600);
INSERT INTO `lg_zone_scale` (`zone_id`, `max_level`) VALUES (1,12),(3,38),(4,55),(8,45),(10,30),(11,30),(12,10),(14,10),(15,45),(16,55),(17,25),(28,55),(33,45),(38,20),(40,20),(41,60),(44,25),(45,40),(46,55),(47,40),(51,50),(65,74),(85,10),(130,20),(139,60),(141,10),(148,20),(215,10),(267,30),(331,25),(357,50),(361,55),(394,76),(400,30),(405,40),(406,25),(440,50),(490,53),(618,60),(1377,60),(3430,10),(3433,20),(3483,63),(3518,67),(3519,65),(3520,70),(3521,64),(3522,68),(3523,70),(3524,10),(3525,20),(3537,72);


-- ---------------------------------------------------------------
-- 3. Mark 61 pending revisions as applied
--    Their structure is in section 1 and their data in section 2.
--    They cannot be replayed: the updater runs files alphabetically
--    but these were written chronologically, and the orders differ.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `updates` (
  `name` varchar(200) NOT NULL,
  `hash` char(40) DEFAULT '',
  `state` enum('RELEASED','CUSTOM','MODULE','ARCHIVED','PENDING') NOT NULL DEFAULT 'RELEASED',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `speed` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_chain_lightning_chaintarget.sql', '935553BDAB35F19C708CE6FBE6DC38522CDA4D91', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_chain_lightning_field_fix.sql', '9057EEB776B7D27900C09C61811714B8AF2351C4', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_chain_lightning_repair.sql', '4778B7BFF20A3BD79ECCC8229E9B11D63FD5EECD', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_dalaran_flight.sql', '81B7FDBBCAFB25B32330202E412AFD8EF172E440', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_dire_maul_no_doors.sql', 'DFDA980D341DBA7095B85D81F04B5AE8720928A4', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_icc_crimson_hall_door.sql', '38A9F16D2D11C1860A8A00122C3EB0CE28C3F9C2', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_lfg_emblem_10x.sql', '2406D1E9F5264A9AE4290BAFC91C301C6A5D427C', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_lfg_legacy_queues.sql', 'F007488EBAD9D3E003B521F6174BCAF39E58FF62', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_lfg_raids.sql', 'A1185CB279E8C587B4C72FDD1564514A0A18F45D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_affliction_contagion.sql', 'CEE1A137238999508F279EBB2C8B2A1DF945C3E5', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_army_of_the_dead.sql', 'C8DB8CD33E4CC434FB1A6AFC3001F5976009BA14', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_auto_mount.sql', 'D27B259D20B1C545051AE4B597DBCA8A79501B9F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_autoloot_dbc.sql', '484019C46A04DE7B1991A23423804DEA7B500E0F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_autoquest_armory.sql', 'E81FB540840182C6ACA5B200F8754AACDF86D935', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_call_of_the_wilds.sql', 'D0D6477D4B54BBF0195779152C727F2B7C879172', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_cc_reduction.sql', '26C424E16B590256D265330BC096D7C060A542FF', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_cleanup_cota.sql', 'BA38C20CF42933EC129D5F89034310E10550829D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_collection_passive.sql', 'EF50EAA8BDA3BEBDC9DAF30409496AA2C04E9118', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_combo_flight.sql', 'D18FE8DB14396005DF4F1536721C040B01626140', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_combo_name.sql', '0EC4C60A8C867A2C0949E091F1B460FC76E1312B', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_combo_redesign.sql', 'D57783598DFA11E3A6668251693CF260AD05E67F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_combo_speed.sql', 'FBF93BFE4EDB07AD1D602551D2CA76E55AB5122A', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_craft_speed.sql', 'BE5EA427AE6CB3924F9C302EF317DE120DE5C419', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_curator_ranks.sql', 'D1858FD1012932734109C40A1029B6B73B8C3768', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_dungeon_timer.sql', 'D0238BC30A88BF20386D063551F42C74CBE42D57', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_gather_021.sql', '2C9327A140E0AA6309BEF722E43CA65BBA893EE5', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_holiday_rotation.sql', '27B017A252075D20A943210F84804CB2FA7F0254', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_jack_in_box_cooldown.sql', '43151E9FBCE3246832B5404D3722F67F99BD3F8D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_jack_in_box_model.sql', '161FFB28F89BB26C7B770FDB881B73C22770C932', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_jack_in_box_target.sql', 'FD207E35675944FD86E12877990B13CDF6288BE5', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_mage_perk_rework.sql', '7926631F406B7FB24B0929A172972ED59C42ED52', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_missing_perk_spells.sql', 'A4B319652D7C89BBA9472F2C0BC4A1545910AFB2', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_mounted_opener.sql', '4D0FCE53DB3105527F75CBFB04B4FA3B0FE6A3BB', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_next_021.sql', '6AB81B8BFA743255189F0D2A4CC8D719FB9E473F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_no_soulbind.sql', '7B1AA07F23F7F8E2C233654EA3278198E7631512', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_perk_names.sql', 'DFB0A13CE29A4196C00F5F6CBC492C445BA417AC', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_perks_npcs.sql', 'BDF890006591D4C8B4E71FF600153033312E3E12', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_pull_radius.sql', '1AD0FAA46C3C9DEC3A499848A9AFB12D7B13CDC4', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_quest_perk_rename.sql', 'F767F02E84DF95B8135A1B803983257C528BE6C1', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_research_no_cooldown.sql', '769B20A68EC097B056613AC2963805D4AE6359F5', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_rogue_perk_wording.sql', '1B303334326E2ACC112AD66CC9E3D59B144BDC8E', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_rogue_rework.sql', '7E91934A6187B19F1404715785DE0EFD629B19DA', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_sanctified_whirlwind.sql', '0FA78BFE578E5F230AE97111B012E1FF22F52926', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_shadow_dance.sql', 'DF9B6BBF456CA60C54AF19E0DF42E1012E23500D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_sunstrider_mailbox.sql', '468CDFDB5BEF549119A21445089A89FE19184933', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_track_gather.sql', '484E8B7C58D7802A2DA81A04354179251898F85E', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_travel_swim.sql', '9834667916F2C57BE19957F56478916767E0F27D', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_visible_buffs.sql', 'AEC1F61F4A9B0A1D4FB4A158C62E679D51858447', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_wayfarer.sql', 'DE5B7E82230BE64EED2806F469457D8F0BCA0DEB', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_wayfarer_speed.sql', '4F0921444A8ED97F98A926CCBDA4F8FCEC42F24A', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_windblown.sql', '2258AD46D977E5F26ECA2A5E39BBD9C886749188', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_zone_scale.sql', '30359018026CD41D628620CEFA59F62CC8E1069F', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_living_gear_zone_scale_data.sql', '48457134CD63B83EA9935EADE0AA41FF9F174B0B', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_pvp_capture_25x.sql', 'B22EBE134CFB8A8D996C0A5C9631621DBE5076DD', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_sfk_courtyard_door.sql', 'CBC95F3AC5BF38721D3D9FBFF7CCF360FD170905', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_weekly_emblem_payout.sql', 'C9671ED6D693E0D1888A7A05F8A6AE81A2BD8AAB', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_wg_currency_10x.sql', '7F1DE55EBB212C062C7FEE2E64A15C5586356E74', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_wg_flight.sql', '237AA1DC789E26A8B621C112B06694E9D1DA908E', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_wg_npc_respawn_30s.sql', '8D23E64A8C17FFE897C3AF40B9771ADB1D98DFCA', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_wg_portal_teleport.sql', '4F35B57B0852C1FF839AFB6727D2226AF5F697DD', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
INSERT INTO `updates` (`name`, `hash`, `state`) VALUES ('rev_wg_shard_loot_10x.sql', '1216AF066D4F7C6DA002C87717F88F367227E096', 'PENDING') ON DUPLICATE KEY UPDATE `hash` = VALUES(`hash`);
